spring:
  datasource:
    url: jdbc:h2:mem:accountDbDev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

server:
  port: 8081

currency:
  exchange:
    server: http://localhost:8080