INSERT INTO customer (id, first_name, last_name, email) VALUES (1, 'John', 'Doe', 'john.doe@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (3, 'Alice', 'Johnson', 'alice.johnson@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (4, 'Robert', 'Brown', 'robert.brown@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (5, 'Michael', 'Davis', 'michael.davis@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (6, 'Emily', 'Wilson', 'emily.wilson@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (7, 'Daniel', 'Taylor', 'daniel.taylor@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (8, 'Sophia', 'Martinez', 'sophia.martinez@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (9, 'James', 'Anderson', 'james.anderson@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (10, 'Charlotte', 'Thomas', 'charlotte.thomas@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (11, 'David', 'Jackson', 'david.jackson@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (12, 'Olivia', 'White', 'olivia.white@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (13, 'Henry', 'Harris', 'henry.harris@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (14, 'Amelia', 'Clark', 'amelia.clark@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (15, 'Logan', 'Lewis', 'logan.lewis@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (16, 'Zoe', 'Walker', 'zoe.walker@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (17, 'Alexander', 'Hall', 'alexander.hall@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (18, 'Isabella', 'Allen', 'isabella.allen@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (19, 'Ethan', 'Young', 'ethan.young@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (20, 'Abigail', 'King', 'abigail.king@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (21, 'Lucas', 'Scott', 'lucas.scott@example.com');
INSERT INTO customer (id, first_name, last_name, email) VALUES (22, 'Shreepal', 'Shekhawat', 'shreepal.shekhawat@example.com');

INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (1, 1, 'ACC11', 'debit', 'USD', 1000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (2, 1, 'ACC12', 'credit', 'EUR', 500.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (3, 2, 'ACC23', 'debit', 'GBP', 750.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (4, 2, 'ACC24', 'credit', 'JPY', 1200.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (5, 3, 'ACC35', 'debit', 'USD', 1500.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (6, 3, 'ACC36', 'credit', 'CAD', 850.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (7, 4, 'ACC47', 'debit', 'USD', 2000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (8, 4, 'ACC48', 'credit', 'AUD', 1100.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (9, 5, 'ACC59', 'debit', 'EUR', 950.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (10, 5, 'ACCI510', 'credit', 'CHF', 300.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (11, 6, 'ACC611', 'debit', 'GBP', 1250.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (12, 6, 'ACC612', 'credit', 'JPY', 1800.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (13, 7, 'ACC713', 'debit', 'USD', 800.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (14, 7, 'ACC714', 'credit', 'NZD', 400.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (15, 8, 'ACC815', 'debit', 'EUR', 1350.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (16, 8, 'ACC816', 'credit', 'HKD', 120.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (17, 9, 'ACC917', 'debit', 'USD', 950.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (18, 9, 'ACC918', 'credit', 'SGD', 670.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (19, 10, 'ACC1019', 'debit', 'GBP', 500.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (20, 10, 'ACC1020', 'credit', 'ZAR', 1000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (21, 11, 'ACC1121', 'debit', 'USD', 1100.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (22, 11, 'ACC1122', 'credit', 'EUR', 600.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (23, 12, 'ACC1223', 'debit', 'USD', 900.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (24, 12, 'ACC1224', 'credit', 'CAD', 400.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (25, 13, 'ACC1325', 'debit', 'GBP', 1250.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (26, 13, 'ACC1326', 'credit', 'JPY', 700.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (27, 14, 'ACC1427', 'debit', 'USD', 1000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (28, 14, 'ACC1428', 'credit', 'AUD', 950.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (29, 15, 'ACC1529', 'debit', 'EUR', 1200.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (30, 15, 'ACC1530', 'credit', 'CHF', 250.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (31, 16, 'ACC1631', 'debit', 'GBP', 1300.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (32, 16, 'ACC1632', 'credit', 'NZD', 820.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (33, 17, 'ACC1733', 'debit', 'USD', 1600.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (34, 17, 'ACC1734', 'credit', 'SGD', 920.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (35, 18, 'ACC1835', 'debit', 'EUR', 1150.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (36, 18, 'ACC1836', 'credit', 'HKD', 600.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (37, 19, 'ACC1937', 'debit', 'USD', 800.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (38, 19, 'ACC1938', 'credit', 'CNY', 100.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (39, 20, 'ACC2039', 'debit', 'EUR', 900.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (40, 20, 'ACC2040', 'credit', 'INR', 1050.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (41, 21, 'ACC2141', 'debit', 'EUR', 5000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (42, 21, 'ACC2142', 'credit', 'INR', 100000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (43, 22, 'ACC2243', 'debit', 'EUR', 50000.00);
INSERT INTO account (id, owner_id, account_number, account_type, currency, balance) VALUES (44, 22, 'ACC2244', 'credit', 'INR', 1000000.00);


